apiVersion: apps/v1
kind: Deployment

metadata:
  name: consumer-temperatura
  namespace: inf1304-g1

spec:
  replicas: 1

  selector:
    matchLabels:
      app: consumer-temperatura

  template:
    metadata:
      labels:
        app: consumer-temperatura

    spec:
      containers:
        - name: consumer-temperatura
          image: mayainha/consumer-service:v1

          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-1:9092,kafka-2:9092,kafka-3:9092"

            - name: KAFKA_TOPIC
              value: "temperatura"

            - name: KAFKA_GROUP_ID
              value: "temperatura-consumer"

            - name: SENSOR_MIN
              value: "10"

            - name: SENSOR_MAX
              value: "35"