apiVersion: apps/v1
kind: Deployment

metadata:
  name: producer-producao
  namespace: inf1304-g1

spec:
  replicas: 1

  selector:
    matchLabels:
      app: producer-producao

  template:
    metadata:
      labels:
        app: producer-producao

    spec:
      containers:
      - name: producer-producao
        image: mayainha/producer-service:v1

        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-1-0.kafka-headless:9092,kafka-2-0.kafka-headless:9092,kafka-3-0.kafka-headless:9092"

        - name: TOPIC_TEMPERATURA
          value: "temperatura"

        - name: TOPIC_VIBRACAO
          value: "vibracao"

        - name: TOPIC_ENERGIA
          value: "energia"

        - name: SENSOR_INTERVAL_MS
          value: "10"

        - name: ANOMALY_PROBABILITY
          value: "0.05"

        - name: SENSOR_SETOR
          value: "producao"

        - name: TEMP_MIN
          value: "20"

        - name: TEMP_MAX
          value: "70"

        - name: VIB_MIN
          value: "0"

        - name: VIB_MAX
          value: "5"

        - name: ENERGIA_MIN
          value: "5"

        - name: ENERGIA_MAX
          value: "50"
